name: UnityBuild
on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
      
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: 'Dockefile'
        description: 'My DockerFile'
        runs:
          using: 'docker'
          image: 'Dockerfile.dockerfile'
      
 
      