name: UnityBuild
on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
      
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: MyTest1
          key: MyTest1
      
      - name: Building
        uses: wlserver1/unityci/action@master
      
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: 
            "build/Android/Android.aab"